dbkey:   # 数据库加密密钥，必须设置

# AES加密用的密钥和XOR，格式为字符串, 设置为空，自动查找
# 示例：aes_xor_key: 1234567890,17
aes_xor_key:

dingtalk:
  # 钉钉机器人Webhook地址，当微信异常时，将推送异常消息和登录二维码
  webhook_url: https://example.com/robot/send?access_token=YOUR_DINGTALK_TOKEN

logging:
  # 日志文件最多保留数量
  backup_count: 5
  # 日志级别，可选：DEBUG/INFO/WARNING/ERROR
  level: INFO
  # 单个日志文件最大字节数
  max_size: 10485760
  # 日志文件存放路径
  path: logs

mqtt:
  # MQTT客户端ID前缀
  client_id: weixin_omni
  # MQTT服务器地址
  host: 127.0.0.1
  # MQTT密码
  password: 'YOUR_MQTT_PASSWORD'
  # MQTT端口
  port: 1883
  # MQTT用户名
  username: weixin

plugins:
  # 图片密钥辅助插件
  image-aes-plugin:
    enabled: true
  # 空群屏蔽插件
  block-empty-room-plugin:
    enabled: true
    priority: 2000
  # 自发消息插件
  self-msg-plugin:
    enabled: true
    priority: 1998
  # 推送消息到MQTT插件（消息日志输出）
  push-msg-to-mqtt:
    enabled: true
    priority: 500

wxgf:
  # 微信GF解析API地址，暂时未开放，查看roammap更新计划
  api_url: http://example.com/api/v1/decrypt

s3:
  # S3存储配置，微信登录二维码将会推送到这里，建议使用CF的R2免费存储，并设置过期时间1天
  endpoint_url: https://example.com
  access_key: YOUR_S3_ACCESS_KEY
  secret_key: YOUR_S3_SECRET_KEY
  region: apac
  bucket: weixin-login-qr
  public_url_prefix: https://example.com/
